version: 2
jobs:
  build:
    docker: 
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: docker build ${IMAGE_NAME}:${CIRCLE_TAG}
  publish:
    docker: 
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish to DockerHub
          command: | 
            echo ${PASSWORD} | docker login -u ${LOGIN} --password-stdin
            docker push ${IMAGE_NAME}:${CIRCLE_TAG}
  
workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags: 
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - publish:
          filters:
            tags: 
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

    
    